#ifndef DEFINES_H_
#define DEFINES_H_

#define APPLE_SOURCE_WIDTH 60
#define APPLE_SOURCE_HEIGHT 60
#define APPLE_MAX_COUNT 8
#define APPLE_SOURCE_RECTANGLE CLITERAL(Rectangle){0, 0, APPLE_SOURCE_WIDTH, APPLE_SOURCE_HEIGHT}

#define BASKET_SOURCE_WIDTH 128
#define BASKET_SOURCE_HEIGHT 128
#define BASKET_SOURCE_RECT CLITERAL(Rectangle){0, 0, BASKET_SOURCE_WIDTH, BASKET_SOURCE_HEIGHT}

#define FALL_SPEED_MIN 150
#define FALL_SPEED_MAX 250

#define TEXT_GAME_OVER "Game Over!"
#define TEXT_RESTART "Press 'R' to Play Again!"

#define TIME_BETWEEN_APPLES 1.0f
#define INITIAL_LIVES 3
#define SCORE_PER_APPLE 100

#define SCREEN_WIDTH 600
#define SCREEN_HEIGHT 600
#define SCREEN_SIZE CLITERAL(Vector2){SCREEN_WIDTH, SCREEN_HEIGHT}

#endif